
package ramirez;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "parcial_1_ramirez_web_operaciones_9a", targetNamespace = "http://ramirez/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Parcial1RamirezWebOperaciones9A {


    /**
     * 
     * @param resistencia
     * @param voltaje
     * @return
     *     returns double
     */
    @WebMethod(operationName = "calcular_intensidad")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcular_intensidad", targetNamespace = "http://ramirez/", className = "ramirez.CalcularIntensidad")
    @ResponseWrapper(localName = "calcular_intensidadResponse", targetNamespace = "http://ramirez/", className = "ramirez.CalcularIntensidadResponse")
    @Action(input = "http://ramirez/parcial_1_ramirez_web_operaciones_9a/calcular_intensidadRequest", output = "http://ramirez/parcial_1_ramirez_web_operaciones_9a/calcular_intensidadResponse")
    public double calcularIntensidad(
        @WebParam(name = "voltaje", targetNamespace = "")
        double voltaje,
        @WebParam(name = "resistencia", targetNamespace = "")
        double resistencia);

}
